### ISSUE TITLE
mac version

### ISSUE THREAD

**Issue by vbauerster** [district10/extended-programmer-dvorak#1]
I'd like to try out on Mac OS X. Is there any support?

**Comment by district10** [comment]
I don't have a mac (yet), so...

But these materials may help:
- [Karabiner - Software for OS X](https://pqrs.org/osx/karabiner/)
- [Modifier key - Wikipedia, the free encyclopedia](https://en.wikipedia.org/wiki/Modifier_key#Dual-role_keys)
- [osx - How can I remap Caps lock to both Escape and Control? - Ask Different](http://apple.stackexchange.com/questions/132564/how-can-i-remap-caps-lock-to-both-escape-and-control)

**Comment by district10** [comment]
My mac keyboard configuration: <https://github.com/district10/neo_keyboard_layout/tree/master/neo4mac>.
